--- #YAML:1.0
name:               Stringify-Deep
version:            0.02
abstract:           Stringifies elements in data structures for easy serialization
author:
    - Michael Aquilina <aquilina@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Structure::Util: 0
    Scalar::Util:          0
no_index:
    directory:
        - t
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4

